spring:
  application:
    name: gateway-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /aggregate/user-service/v3/api-docs
      - name: Match Service
        url: /aggregate/match-service/v3/api-docs
  api-docs:
    path: /api-docs