spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  flyway:
    schemas: ${FLYWAY_SCHEMA:public}
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: kafka-1:9090,kafka-2:9090,kafka-3:9090

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 20000 # максимальное время на повторы отправки. сколько по времени ждём акнолеждмент от всех инсинк реплик
        linger:
          ms: 0
        request:
          timeout:
            request:
              ms: 10000 # как долго ждём акноледжмент отправив сообщение. потом таймаут и делаем ритрай

user:
  url: http://user-service:8080

resilience4j:
  circuitbreaker:
    instances:
      user:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    instances:
      userServiceCircuitBreaker:
        timeout-duration: 3s
  retry:
    instances:
      userServiceCircuitBreaker:
        max-attempts: 3
        wait-duration: 5s